sed -i 's/\r//' ./batchFreePasswordLogin/batchSSHFreePasswordLogin.sh
sed -i 's/\r//' ./batchChangeHostName/batchChangeHostname.sh
sed -i 's/\r//' ./batchChangeHosts/batchChangeHosts.sh
sed -i 's/\r//' ./batchCloseFirewallAndSelinux/batchCloseFirewallAndSelinux.sh
sed -i 's/\r//' ./batchSetTimeZone/batchSetTimeZone.sh
sed -i 's/\r//' ./batchClockSynchronization/batchClockSynchronization.sh
sed -i 's/\r//' ./batchCloseTransparentHugePage/batchCloseTransparentHugePage.sh
sed -i 's/\r//' ./batchChangeSwappiness/batchChangeSwappiness.sh
sed -i 's/\r//' ./batchInstallLocalYumRepository/batchInstallLocalYumRepository.sh
sed -i 's/\r//' ./installDockerAndCompose/installDockerAndCompose.sh
sed -i 's/\r//' ./installMysql/installMysql.sh
sed -i 's/\r//' ./batchInstallJDK/batchInstallJDK.sh
sed -i 's/\r//' ./installCM/batchInstallCMAgent.sh
sed -i 's/\r//' ./installCM/installCMServer.sh